services:
    fluxloader:
        image: ghcr.io/fluxloader-team/fluxloader-site:lateste
        # In our production environment we using container name and docker dns to resolve the ip of the container
        container_name: fluxloader
        restart: unless-stopped
        # Docker will load .env files and populate them into environment vars
        environment:
            - DISCORD_CLIENTID=${DISCORD_CLIENTID}
            - DISCORD_CLIENTSECRET=${DISCORD_CLIENTSECRET}
            - DISCORD_REDIRECTURI=${DISCORD_REDIRECTURI}
            - DISCORD_TOKEN=${DISCORD_TOKEN}
            - DISCORD_RUNBOT=${DISCORD_RUNBOT}
            - DISCORD_SERVERLOG=${DISCORD_SERVERLOG}
            - DISCORD_SERVERLOGCHANNEL=${DISCORD_SERVERLOGCHANNEL}
            - DISCORD_SERVERACTIONSCHANNEL=${DISCORD_SERVERACTIONSCHANNEL}
            - DISCORD_SERVER=${DISCORD_SERVER}

            # Should resolve to the mongo container
            - MONGODB_URI=mongodb://mongo:27017/
            - GIT_PULL=${GIT_PULL}
            - MODSETTINGS_VALIDATIONTIME=${MODSETTINGS_VALIDATIONTIME}
            - REQUIREGITHUBSECRETFORRELOAD=${REQUIREGITHUBSECRETFORRELOAD}
            - GITHUBSECRET=${GITHUBSECRET}
        depends_on:
            - mongo

    nginx:
        image: nginx:1.30-alpine
        container_name: nginx
        ports:
            - 443:443
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/certs:/etc/nginx/certs:ro
        depends_on:
            - nginx

    mongo:
        image: mongo:8.0-noble
        container_name: mongo
        volumes:
            - mongodb:/data/db

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        #* Ports to expose if not using a reverse proxy
        # ports:
        #   - 8081:8081
        environment:
            #! In our production environment this is protected via cloudflare access.
            # This setting should be modified as per your own environment
            - ME_CONFIG_BASICAUTH_ENABLED=false
        depends_on:
            - mongo

volumes:
    mongodb:
