services:
    fluxloader:
        image: ghcr.io/fluxloader-team/fluxloader-site:latest
        # In our production environment we using container name and docker dns to resolve the ip of the container
        container_name: fluxloader
        restart: unless-stopped
        # Docker will load .env files and populate them into environment vars
        environment:
            - CONFIG_DISCORD_CLIENTID=${CONFIG_DISCORD_CLIENTID}
            - CONFIG_DISCORD_CLIENTSECRET=${CONFIG_DISCORD_CLIENTSECRET}
            - CONFIG_DISCORD_REDIRECTURI=${CONFIG_DISCORD_REDIRECTURI}
            - CONFIG_DISCORD_TOKEN=${CONFIG_DISCORD_TOKEN}
            - CONFIG_DISCORD_RUNBOT=${CONFIG_DISCORD_RUNBOT}
            - CONFIG_DISCORD_SERVERLOG=${CONFIG_DISCORD_SERVERLOG}
            - CONFIG_DISCORD_SERVERLOGCHANNEL=${CONFIG_DISCORD_SERVERLOGCHANNEL}
            - CONFIG_DISCORD_SERVERACTIONSCHANNEL=${CONFIG_DISCORD_SERVERACTIONSCHANNEL}
            - CONFIG_DISCORD_SERVER=${CONFIG_DISCORD_SERVER}

            # Should resolve to the mongo container
            - CONFIG_MONGODB_URI=mongodb://mongo:27017/
            - CONFIG_GIT_PULL=${CONFIG_GIT_PULL}
            - CONFIG_MODSETTINGS_VALIDATIONTIME=${CONFIG_MODSETTINGS_VALIDATIONTIME}
            - CONFIG_REQUIREGITHUBSECRETFORRELOAD=${CONFIG_REQUIREGITHUBSECRETFORRELOAD}
            - CONFIG_GITHUBSECRET=${CONFIG_GITHUBSECRET}
        depends_on:
            - mongo

    nginx:
        image: nginx:1.30-alpine
        container_name: nginx
        ports:
            - 443:443
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/certs:/etc/nginx/certs:ro
        depends_on:
            - fluxloader

    mongo:
        image: mongo:8.0-noble
        container_name: mongo
        volumes:
            - mongodb:/data/db

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        #* Ports to expose if not using a reverse proxy
        # ports:
        #   - 8081:8081
        environment:
            #! In our production environment this is protected via cloudflare access.
            # This setting should be modified as per your own environment
            - ME_CONFIG_BASICAUTH_ENABLED=false
        depends_on:
            - mongo

volumes:
    mongodb:
