events {
  worker_connections 4096; ## Default: 1024
}

http {
  keepalive_timeout 900;
  keepalive_requests 100;

  proxy_buffering on;


  # fluxloader.highlyflammable.tech (testing) + fluxloader.app
  server {
     ssl_certificate /etc/nginx/certs/localhost.crt;
     ssl_certificate_key /etc/nginx/certs/localhost.key;

    listen 443 ssl;
    listen [::]:443 ssl;
    server_name fluxloader.highlyflammable.tech fluxloader.app;


    location / {
      # https://docs.docker.com/engine/network/#dns-services
      resolver 127.0.0.11;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      # Docker DNS should resolve to the ip via the resolver. The port is what's being used in the container not whats being forwarded to the host
      proxy_pass http://fluxloader:20221$request_uri;
    }
  }

  # preventing direct ip access
  server {
    ssl_certificate /etc/nginx/certs/localhost.crt;
    ssl_certificate_key /etc/nginx/certs/localhost.key;
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;

    server_name _;

    keepalive_timeout 0;
    return 444;
  }
}
